#!/usr/bin/env python3
"""Regenerate the two reference files that describe syntax.

END-TO-END FLOW of this script:

  1. It imports the server's FastAPI app and asks it for its own OpenAPI
     document. That document is built from the pydantic models, so it is the
     server's actual contract rather than a description of it.
  2. It renders that into `agent/references/api.md`.
  3. It walks the CLI's argument parser and renders every subcommand and flag
     into `agent/references/cli.md`. It does NOT capture `--help` text: that
     wraps to the terminal width and changed shape in Python 3.13, so it
     differed between a laptop and the CI runner. See `render_cli`.
  4. `--check` compares what it would write against what is on disk and exits 1
     if they differ. CI runs that, so a route or a flag cannot change without
     the references changing with it.

WHY GENERATE RATHER THAN WRITE. The split is SkyPilot's and it is the right one:
**syntax comes from the code, pitfalls are written by hand.** A hand-written
list of routes is a second source of truth, and the second source is always the
one that is out of date. `script-contract.md` and `troubleshooting.md` are the
hand-written half and this script never touches them.

NO MODEL IS INVOLVED. Everything here is reading a data structure and printing
it. That is what makes the CI check meaningful: the output is deterministic.

Run it from the repository root:

    python3 agent/scripts/generate_references.py
    python3 agent/scripts/generate_references.py --check

Grep anchor: DDPSRUN-GENERATE-REFERENCES
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
REFERENCES = REPO_ROOT / "agent" / "references"

# Both packages live in this repository but are not installed as one, so the
# generator puts them on the path itself rather than requiring a particular
# virtual environment.
sys.path.insert(0, str(REPO_ROOT / "server"))
sys.path.insert(0, str(REPO_ROOT / "cli"))

BANNER = (
    "<!-- GENERATED by agent/scripts/generate_references.py. Do not edit. -->\n"
    "<!-- Pitfalls and advice go in script-contract.md and troubleshooting.md. -->\n"
)


def render_api() -> str:
    """Turn the server's OpenAPI document into a reference page.

    Returns:
        Markdown.

    The server is imported without starting it: FastAPI builds the OpenAPI
    document from the route signatures, which needs no configuration, no token
    file and no cluster.
    """
    from ddpsrun_server.main import app

    document = app.openapi()
    lines = [
        BANNER,
        "# API reference",
        "",
        f"Generated from the server's own OpenAPI document, version "
        f"{document['info']['version']}.",
        "",
        "Every route except `/healthz`, `/v1/explain` and `/v1/schema` needs a header:",
        "",
        "```",
        "Authorization: Bearer <your token>",
        "```",
        "",
        "## Routes",
        "",
        "| method | path | what it does |",
        "|---|---|---|",
    ]

    for path in sorted(document["paths"]):
        for method, operation in sorted(document["paths"][path].items()):
            # `summary` is FastAPI's title-cased version of the function name
            # ("Estimate Route"), which says nothing. The route's docstring
            # lands in `description`, and its first line is the sentence that
            # was written to be read.
            description = (operation.get("description") or "").strip()
            first_line = description.split("\n")[0].strip()
            lines.append(
                f"| {method.upper()} | `{path}` | "
                f"{first_line or (operation.get('summary') or '').strip()} |"
            )

    lines += ["", "## Request and response shapes", ""]

    for name in sorted(document.get("components", {}).get("schemas", {})):
        schema = document["components"]["schemas"][name]
        lines += [f"### {name}", ""]
        if schema.get("description"):
            # Only the first paragraph: the rest of a model's docstring is
            # written for someone reading the source, not calling the API.
            lines += [schema["description"].split("\n\n")[0].strip(), ""]
        properties = schema.get("properties") or {}
        if not properties:
            continue
        required = set(schema.get("required") or [])
        lines += ["| field | required | description |", "|---|---|---|"]
        for field in sorted(properties):
            description = (properties[field].get("description") or "").replace("\n", " ").strip()
            mark = "yes" if field in required else ""
            lines.append(f"| `{field}` | {mark} | {description} |")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _flag_names(action: object) -> str:
    """How one option is written on a command line.

    Args:
        action: an argparse action.

    Returns:
        Its option strings joined, with the metavar where a value goes.
    """
    import argparse

    if not action.option_strings:
        return f"`{action.metavar or action.dest}`"

    takes_value = not isinstance(
        action, (argparse._StoreTrueAction, argparse._StoreFalseAction, argparse._HelpAction)
    )
    value = ""
    if takes_value:
        value = " " + (action.metavar or action.dest.upper())
    return ", ".join(f"`{name}{value}`" for name in action.option_strings)


def _options_table(parser: object) -> list[str]:
    """Render one parser's arguments as a table.

    Args:
        parser: an ArgumentParser.

    Returns:
        Markdown lines, or an empty list when it takes nothing but `--help`.
    """
    import argparse

    rows = []
    for action in parser._actions:
        if isinstance(action, (argparse._HelpAction, argparse._SubParsersAction)):
            continue
        default = ""
        if action.default not in (None, False) and not isinstance(action.default, list):
            default = f" (default `{action.default}`)"
        help_text = (action.help or "").replace("\n", " ").strip()
        required = "yes" if getattr(action, "required", False) or not action.option_strings else ""
        rows.append(f"| {_flag_names(action)} | {required} | {help_text}{default} |")

    if not rows:
        return []
    return ["| argument | required | what it does |", "|---|---|---|", *rows, ""]


def render_cli() -> str:
    """Turn the CLI's argument parser into a reference page.

    Returns:
        Markdown.

    WHY THIS WALKS THE PARSER INSTEAD OF CAPTURING `--help`. Capturing was the
    first version and CI rejected it, correctly. `--help` text is wrapped to
    `shutil.get_terminal_size()`, and Python 3.13 changed how argparse prints an
    option that has both a short and a long form (`-f, --file FILE` where 3.12
    wrote `-f FILE, --file FILE`). So the output differed between a developer's
    machine and the runner, and **a generated artefact that CI checks has to be
    identical everywhere or the check means nothing**. Reading the actions
    themselves depends on neither.
    """
    import argparse

    from ddpsrun.cli import build_parser

    parser = build_parser()
    lines = [
        BANNER,
        "# CLI reference",
        "",
        "Generated from `ddpsrun`'s own argument parser.",
        "",
        "```",
        "ddpsrun <command> [options]",
        "```",
        "",
        "## Commands",
        "",
        "| command | what it does |",
        "|---|---|",
    ]

    subactions = [
        action for action in parser._actions
        if isinstance(action, argparse._SubParsersAction)
    ]
    choices: dict[str, object] = {}
    for action in subactions:
        # `choices` preserves the order the subcommands were added, which is the
        # order they are meant to be used in.
        choices.update(action.choices)
        for entry in action._choices_actions:
            lines.append(f"| `ddpsrun {entry.dest}` | {(entry.help or '').strip()} |")

    lines.append("")

    for name, subparser in choices.items():
        lines += [f"## ddpsrun {name}", ""]
        description = (subparser.description or "").replace("\n", " ").strip()
        if description:
            lines += [description, ""]
        lines += _options_table(subparser)

    lines += [
        "## Exit codes",
        "",
        "| code | meaning |",
        "|---|---|",
        "| 0 | it worked |",
        "| 1 | the server refused, or could not be reached. `validate` also uses "
        "this when a finding would actually stop the job |",
        "| 2 | the command was wrong, or there are no credentials |",
        "",
    ]
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    """Write the two files, or check them.

    Args:
        argv: arguments without the program name.

    Returns:
        0 when everything is in order, 1 when `--check` found a difference.
    """
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if what is on disk differs from what would be written",
    )
    args = parser.parse_args(argv)

    wanted = {REFERENCES / "api.md": render_api(), REFERENCES / "cli.md": render_cli()}

    stale: list[Path] = []
    for path, content in wanted.items():
        existing = path.read_text(encoding="utf-8") if path.exists() else None
        if existing == content:
            continue
        if args.check:
            stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(REPO_ROOT)}")

    if stale:
        print(
            "stale: " + ", ".join(str(path.relative_to(REPO_ROOT)) for path in stale),
            file=sys.stderr,
        )
        print(
            "run `python3 agent/scripts/generate_references.py` and commit the result",
            file=sys.stderr,
        )
        return 1
    if args.check:
        print("references are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
