"""Generate aws_gpus.csv, the table machine.py reads: which GPU each AWS instance type carries.

WHY THIS TABLE EXISTS (HYPERUN-INSTANCE-AND-GPU). On AWS the only name a job's status
holds for what it runs on is the EC2 instance type (status.currentOffering.instanceType,
"g6.2xlarge"), and the GPU model is not part of that name. The console has to show the
GPU separately from the machine, so it needs instance type -> GPU model.

WHY NOT prices.csv. That file keeps, per (card, count, region), the machine the
estimate would price, so most instance types never appear in it: on 2026-10-08 the
jobs on the cluster had run on g6.2xlarge and gr6.4xlarge, and prices.csv knows
neither. This table is every AWS instance type the SkyPilot catalogue lists with an
accelerator, whatever its price.

ONE ROW PER INSTANCE TYPE. The catalogue repeats a type once per zone; the
accelerator never differs between those rows, and the generator refuses to write a
table if it ever does.

The count column is the catalogue's AcceleratorCount: GPUs on the whole machine,
which may be a fraction for a partitioned card (g6f). The console does not show this
count; it shows the job's own request per pod.

Run: python tools/gen_aws_gpus.py > ddpsrun_server/aws_gpus.csv
"""
import csv
import datetime
import os
import pathlib
import sys

CATALOGUE = pathlib.Path(os.path.expanduser("~/.sky/catalogs/v8/aws/vms.csv"))


def main() -> int:
    seen: dict[str, tuple[str, str]] = {}
    with CATALOGUE.open(newline="") as handle:
        for row in csv.DictReader(handle):
            name = (row.get("AcceleratorName") or "").strip()
            if not name:
                continue
            raw = (row.get("AcceleratorCount") or "").strip()
            count = f"{float(raw):g}" if raw else ""
            instance = row["InstanceType"].strip()
            pair = (name, count)
            if seen.get(instance, pair) != pair:
                print(f"{instance}: the catalogue names two accelerators, "
                      f"{seen[instance]} and {pair}; not writing a table",
                      file=sys.stderr)
                return 1
            seen[instance] = pair

    read_on = datetime.date.fromtimestamp(CATALOGUE.stat().st_mtime).isoformat()
    out = csv.writer(sys.stdout, lineterminator="\n")
    print(f"# generated by tools/gen_aws_gpus.py from ~/.sky/catalogs/v8/aws/vms.csv "
          f"(file dated {read_on}). Do not hand-edit.")
    out.writerow(["instance", "gpu", "count"])
    for instance in sorted(seen):
        out.writerow([instance, *seen[instance]])
    return 0


if __name__ == "__main__":
    sys.exit(main())
