"""What a job runs on, as two values: the machine and the GPU (HYPERUN-INSTANCE-AND-GPU).

THE PROBLEM. A job's status keeps ONE name for what it runs on,
status.currentOffering.instanceType, and the vendor decides what that name means.
Read on 2026-10-08 from the 99 HyperunJobs on the cluster:

  aws        an EC2 instance type: "t3.xlarge", "g6.2xlarge". The GPU is not in it.
  gcp        machine type, "+", GPU model, ":", count: "g2-standard-4+L4:1".
  shadeform  "<cloud>_<GPU>[x<count>]": "massedcompute_L40S", "crusoe_A100-80GBx4".
  runpod     the GPU type itself: "NVIDIA A100-SXM4-80GB". RunPod rents a pod by GPU
             type and has no instance type at all.

The API handed that one value out as `gpu`, and the console printed it under the label
"GPU". So a CPU job read "GPU  t3.xlarge", which names a machine, not a GPU.

WHAT THIS MODULE RETURNS. The machine (`instance`) and the GPU model (`gpu_model`), split
per vendor by the rules above, and the GPU count per pod (`gpu_count`), which is the
job's own request and not part of any vendor's name. A job that asked for no GPU has no
GPU model and no count, whatever the machine carries, so the console can leave the GPU
line out.

`gpu` stays in the API with its old value. CLI 0.2.7 and older print it as
"running on <gpu>", and a client already installed cannot be changed from here.
"""
from __future__ import annotations

import csv
import pathlib
import re
from dataclasses import dataclass
from functools import lru_cache
from typing import Any

from . import measurements

AWS_GPUS_FILE = "aws_gpus.csv"

# A count suffix on a Shadeform instance name: "crusoe_A100-80GBx4" -> "x4".
_SHADEFORM_COUNT = re.compile(r"x\d+$")


@dataclass(frozen=True)
class MachineAndGpu:
    """What a job runs on.

    Attributes:
        instance: the vendor's own name for the machine. None on RunPod (no
            instance type there) and before a machine exists.
        gpu_model: the GPU model the job got, e.g. "L4". None for a job that
            asked for no GPU, and before a machine exists.
        gpu_count: GPUs per pod, as the job asked. None for a job that asked
            for no GPU.
    """

    instance: str | None
    gpu_model: str | None
    gpu_count: int | None


@lru_cache(maxsize=1)
def _aws_gpus() -> dict[str, str]:
    """Read aws_gpus.csv (instance type -> GPU model), once.

    The file sits beside this module and ships in the package (pyproject's
    package-data takes every *.csv). It is generated by tools/gen_aws_gpus.py.
    A missing file raises: a table that silently reads as empty would make every
    AWS GPU job look like it had no GPU.
    """
    path = pathlib.Path(__file__).with_name(AWS_GPUS_FILE)
    with path.open(newline="") as handle:
        rows = csv.DictReader(line for line in handle if not line.startswith("#"))
        return {row["instance"]: row["gpu"] for row in rows}


@lru_cache(maxsize=1)
def _shadeform_cards() -> dict[str, str]:
    """Shadeform instance name -> card, from the rows prices.csv already holds."""
    return {row.instance: row.card for row in measurements.PRICE_ROWS
            if row.vendor == "shadeform" and row.instance}


@lru_cache(maxsize=1)
def _known_cards() -> frozenset[str]:
    """Every card name prices.csv uses, any vendor."""
    return frozenset(row.card for row in measurements.PRICE_ROWS if row.card)


def requested_gpus(spec: dict[str, Any]) -> tuple[int | None, str | None]:
    """How many GPUs per pod the job asked for, and the model it named.

    Args:
        spec: the HyperunJob's spec.

    Returns:
        (count, name). (None, None) for a job that asked for no GPU. The CRD fills
        an omitted count with 1, so an absent count on a GPU request reads as 1.
    """
    gpus = (spec.get("resources") or {}).get("gpus")
    if not isinstance(gpus, dict) or not gpus:
        return None, None
    count = int(gpus.get("count") or 1)
    if count <= 0:
        return None, None
    name = gpus.get("name") or None
    return count, (str(name) if name else None)


def split_offering(vendor: str | None, instance_type: str | None,
                   requested_name: str | None = None) -> tuple[str | None, str | None]:
    """Split a vendor's one name for what was rented into (machine, GPU model).

    Args:
        vendor: status.currentOffering.vendor.
        instance_type: status.currentOffering.instanceType.
        requested_name: the GPU model the job named, used only on AWS when the
            table has no row for the instance type.

    Returns:
        (instance, gpu_model). Both None when nothing was rented yet. gpu_model
        is the machine's GPU; whether the JOB uses one is for the caller to say.
    """
    if not instance_type:
        return None, None
    v = (vendor or "").lower()
    if v == "runpod":
        model = instance_type
        for maker in ("NVIDIA ", "AMD "):
            if model.startswith(maker):
                model = model[len(maker):]
        return None, model.strip() or None
    if v == "gcp":
        machine, _, accelerator = instance_type.partition("+")
        model = accelerator.split(":", 1)[0] if accelerator else ""
        return machine or None, model or None
    if v == "shadeform":
        card = _shadeform_cards().get(instance_type)
        if not card:
            _, sep, rest = instance_type.partition("_")
            card = _SHADEFORM_COUNT.sub("", rest if sep else instance_type)
            # A size variant the price table has never seen: Massed Compute's
            # "A6000-plus" is an A6000 in a bigger machine. When the job named
            # the card and the leftover only extends that name with "-...", the
            # named card is the GPU. A card the table knows is left as it is, so
            # "A100-80GB" is never cut back to an ask of "A100".
            if (requested_name and card not in _known_cards()
                    and card.lower().startswith(requested_name.lower() + "-")):
                card = requested_name
        return instance_type, card or None
    if v == "aws":
        return instance_type, _aws_gpus().get(instance_type) or requested_name
    # A vendor this module has not met: keep the name as the machine, and the
    # model only if the job named one.
    return instance_type, requested_name


def machine_and_gpu(offering: dict[str, Any], spec: dict[str, Any]) -> MachineAndGpu:
    """What a job runs on, split into machine and GPU.

    Args:
        offering: status.currentOffering ({} before a machine exists).
        spec: the HyperunJob's spec.

    Returns:
        MachineAndGpu. A job that asked for no GPU gets gpu_model None even when
        its machine has one: the console must not say "GPU" for a job that has
        none.
    """
    count, name = requested_gpus(spec)
    instance, model = split_offering(offering.get("vendor"),
                                     offering.get("instanceType"), name)
    if count is None:
        model = None
    return MachineAndGpu(instance=instance, gpu_model=model, gpu_count=count)
